---
- name: Simple playbook to install stuff
  hosts: srv1
  become: yes

  tasks:
  - name: Install epel
    dnf:
      name: epel-release
      state: present

  - name: Install Apache Web Server
    dnf:
      name: httpd
      state: present

  - name: Ensure Apache is running
    service:
      name: httpd
      state: started
      enabled: yes