---
- name: Simple playbook to install stuff
  hosts: srv1
  become: yes
  vars:
    - picture: Hobbit1.png
    - index_file: index.html

  tasks:
  - name: Install epel
    dnf:
      name: epel-release
      state: present

  - name: Install Apache Web Server
    dnf:
      name:
        - httpd
        - wget
        - bzip2
      state: present

  - name: Add an Index html file
    get_url:
      url: "{{ index_file }}"
      dest: /var/www/html/
      owner: apache
      group: apache

  - name: Grab Image File
    get_url:
      url: "{{ picture }}"
      dest: /var/www/html/
      owner: apache
      group: apache

  - name: Ensure Apache is running
    service:
      name: httpd
      state: restarted
      enabled: yes